title: 'Church of Wifi'
description: "a shifty church for shifty people"
baseurl: "/"
url: "https://churchofwifi.org"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://twitter.com/churchofwifi.org">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

# github setting
repository: DEFCON-MUD/DEFCON-MUD